functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - На странице корзины пользователь может удалить товар из корзины
  - Пользователь может оформить заказ с переходом на страницу оплаты
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт - это SPA приложение, которое не перезагружает страницу
  - Сайт должен обладать постраничным выводом списка товаров для покупки
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - Корзина хранится в сессии браузера
implicit:
  - Фильтр по цене должен в подсказке показывать максимально возможную цену, которая есть в базе магазина.
  - Должна быть локализация - русская и английская
  - На главной странице должен быть индикатор того, что в корзину уже что-то добавлено. Выводить количество товаров рядом с Корзиной в меню
  - Описание товара должно быть в виде свойств, перечень которых удобен для чтения
  - Товар должен содержать фото, превью фото, галерею фото
  - Пользователь должен иметь возможность добавить товар на странице просмотра информации о товаре.
  - Должна сохраняться пропорция фотографий товаров при отображении их пользователям.
  - Пользователь должен иметь возможность отбирать товары, которые есть в наличии.
  - После успешной оплаты товаров в корзине она должна очищаться 
  - Итоговая сумма товаров в корзине должна пересчитываться после добавления или удаления товаров в ней
  - Пользователь должен иметь возможность при добавлении товара указать количество товара, которое он намерен купить
  - Пользователь должен иметь возможность увеличить или уменьшить количество товара, который он добавил в корзину
  - При добавлении товара, который уже есть в корзине, должно увеличиваться количество товара у приобретаемой позиции в списке товаров корзины
  - Должна быть возможность оставить оценку товару после оплаты
  - Фотографии товара в галерее должны быть приведены к одному размеру
  - Должен быть виден остаток товара на странице магазина и на странице просмотра товара
  - Должно контролироваться количество товара, которое пользователь пытается добавить в корзину и должно появляться предупреждение, если нет столько единиц товара, сколько пользователь хочет добавить. Данный контроль должен осуществляться как при добавлении товара в корзину, так и при оплате.
  - Добжна быть возможность просмотреть все свои оплаченные ордера
  - Должна быть авторизация по логину и паролю 
  - Должна быть регистрация пользователя с указанием контактного номера телефона
  - Длина логина должна быть не меньше 6 символов. Длина пароля не меньше 6 символов, обязательно наличие символов в верхнем регистре и цифр. Иные символы не допустимы.
  - Должна быть возможность восстановить пароль
  - Пользователь должен иметь возможность сменить номер телефона в настройках своего профиля
  - Пользователь должен иметь возможность выбрать товары с остатком
  - При покупке товара количество товара на остатке должно уменьшаться
  - Значения фильтров и заданных условий отборов не должны удаляться, если пользователь зашел в просмотр товара. После возврата со страницы товара в список товаров его содержимое должно соответствовать условиям фильтров и отборов
  - Список брендов в фильтре должен меняться в зависимости от того, какие товары остались на странице товаров после применения фильтра по цене/категории.
  - По умолчанию устанавливать пользователю английский язык при входе на сайт, если он не из РФ 
  - У пользователя должна быть возможность выбрать товары по всем категориям
