functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - На странице корзины пользователь может удалить товар из корзины
  - Пользователь может оформить заказ с переходом на страницу оплаты
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт - это SPA приложение, которое не перезагружает страницу
  - Сайт должен обладать постраничным выводом списка товаров для покупки
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - Корзина хранится в сессии браузера
implicit:
  - Фильтр по цене должен в подсказке показывать максимально возможную цену, которая есть в базе магазина.
  - Должна быть локализация - русская и английская
  - На главной странице должен быть индикатор того, что в корзину уже что-то добавлено. Выводить количество товаров рядом с Корзиной в меню
  - Описание товара должно быть в виде свойств, перечень которых удобен для чтения
  - Товар должен содержать фото, превью фото, галерею фото
  - Пользователь должен иметь возможность добавить товар на странице просмотра информации о товаре.
  - Должна сохраняться пропорция фотографий товаров при отображении их пользователям.
  - Пользователь должен иметь возможность отбирать товары, которые есть в наличии.
  - После успешной оплаты товаров в корзине она должна очищаться 
  - Итоговая сумма товаров в корзине должна пересчитываться после добавления или удаления товаров в ней
  - Пользователь должен иметь возможность при добавлении товара указать количество товара, которое он намерен купить
  - Пользователь должен иметь возможность увеличить или уменьшить количество товара, который он добавил в корзину
  - При добавлении товара, который уже есть в корзине, должно увеличиваться количество товара у приобретаемой позиции в списке товаров корзины
  
