functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - На странице корзины пользователь может удалить товар из корзины
  - Пользователь может оформить заказ с переходом на страницу оплаты
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт - это SPA приложение, которое не перезагружает страницу
  - Сайт должен обладать постраничным выводом списка товаров для покупки
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - Корзина хранится в сессии браузера
implicit:
  - После успешной оплаты товаров в корзине она должна очищаться 
  - Должна быть возможность оставить оценку товару после оплаты
  - Должно контролироваться количество товара, которое пользователь пытается добавить в корзину. Данный контроль должен осуществляться как при добавлении товара в корзину, так и при оплате.
  - Должна быть возможность просмотреть все свои оплаченные ордера
  - Должна быть авторизация по логину и паролю 
  - Должна быть регистрация пользователя с указанием контактного номера телефона
  - Длина логина должна быть не меньше 6 символов. Длина пароля не меньше 6 символов, обязательно наличие символов в верхнем регистре и цифр. Иные символы не допустимы.
  - Должна быть возможность восстановить пароль
  - Пользователь должен иметь возможность сменить номер телефона в настройках своего профиля
  - При покупке товара количество товара на остатке должно уменьшаться
